services:
  - type: web
    name: fintrack-pro-backend
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: DB_SSLMODE
        value: require
      - key: ALLOWED_ORIGINS
        sync: false
